import { useEffect, useState } from 'react';
import type { ChangeEvent } from 'react';
import { Link } from 'react-router-dom';
import {
  IconFileCheck,
  IconSparkles,
  IconCheckCircle,
  IconClock,
  IconArrowRight,
  IconRotateCcw,
  IconUserCheck,
  IconShieldCheck,
  IconAlertCircle,
  IconCpu,
  IconLayers,
} from '../components/Icons';
import {
  confirmSystemCard,
  getSystemCard,
  postCardDrafts,
  SystemCardData,
} from '../api';
import '../styles/card.css';

export function Card() {
  const [card, setCard] = useState<SystemCardData | null>(null);
  const [intendedUse, setIntendedUse] = useState<string>('');
  const [knownLimits, setKnownLimits] = useState<string>('');
  const [confirmedBy, setConfirmedBy] = useState<string>('Jane Doe (AI Safety Lead)');
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [isRegenerating, setIsRegenerating] = useState<boolean>(false);
  const [isConfirming, setIsConfirming] = useState<boolean>(false);
  const [feedbackNote, setFeedbackNote] = useState<string | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  async function loadCard() {
    try {
      const data = await getSystemCard();
      setCard(data);
      setIntendedUse(data.intended_use);
      setKnownLimits(data.known_limits);
      if (data.confirmed_by) {
        setConfirmedBy(data.confirmed_by);
      }
      setErrorMessage(null);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : 'Load failed';
      setErrorMessage(`Failed to load system card: ${msg}`);
    } finally {
      setIsLoading(false);
    }
  }

  useEffect(() => {
    loadCard();
  }, []);

  async function handleRegenerateDrafts() {
    setIsRegenerating(true);
    setFeedbackNote(null);
    setErrorMessage(null);

    try {
      const updated = await postCardDrafts();
      setCard(updated);
      setIntendedUse(updated.intended_use);
      setKnownLimits(updated.known_limits);
      setFeedbackNote('Drafts successfully regenerated by LLM');
      setTimeout(() => setFeedbackNote(null), 3000);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : 'Regeneration failed';
      setErrorMessage(`Failed to regenerate drafts: ${msg}`);
    } finally {
      setIsRegenerating(false);
    }
  }

  async function handleConfirmCard() {
    if (!confirmedBy.trim()) {
      setErrorMessage('Please provide a reviewer name to confirm the card.');
      return;
    }

    setIsConfirming(true);
    setFeedbackNote(null);
    setErrorMessage(null);

    try {
      const confirmed = await confirmSystemCard(confirmedBy, intendedUse, knownLimits);
      setCard(confirmed);
      setFeedbackNote('System Card confirmed & digitally sealed');
      setTimeout(() => setFeedbackNote(null), 4000);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : 'Confirmation failed';
      setErrorMessage(`Failed to confirm card: ${msg}`);
    } finally {
      setIsConfirming(false);
    }
  }

  function formatDate(isoString: string | null): string {
    if (!isoString) return '';
    try {
      const d = new Date(isoString);
      return d.toLocaleDateString('en-GB', {
        day: 'numeric',
        month: 'short',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      });
    } catch {
      return isoString;
    }
  }

  return (
    <div className="page-container card-screen">
      {/* Header */}
      <div className="card-hero">
        <div className="card-hero-left">
          <div className="badge badge-accent" style={{ marginBottom: 'var(--space-2)' }}>
            <IconFileCheck size={12} />
            <span>Phase 2: Model Specification</span>
          </div>
          <h1 className="page-title">
            <span>{card?.title || 'AI System Card'}</span>
          </h1>
          <p className="page-description">
            The canonical factual specification for the evaluation target. Derived from intake responses and governance policies.
          </p>
        </div>

        {card && (
          <div>
            {card.status === 'confirmed' ? (
              <div className="card-status-badge confirmed">
                <IconCheckCircle size={16} />
                <span>Confirmed and Verified</span>
              </div>
            ) : (
              <div className="card-status-badge draft">
                <IconClock size={16} />
                <span>Draft: Sign-off Required</span>
              </div>
            )}
          </div>
        )}
      </div>

      {errorMessage && (
        <div className="conflict-alert-card" style={{ marginBottom: 'var(--space-4)' }}>
          <div className="conflict-alert-title">
            <IconAlertCircle size={16} />
            <span>{errorMessage}</span>
          </div>
        </div>
      )}

      {feedbackNote && (
        <div className="conflict-cleared-card" style={{ marginBottom: 'var(--space-4)' }}>
          <IconCheckCircle size={16} />
          <span>{feedbackNote}</span>
        </div>
      )}

      {isLoading ? (
        <div className="card-dossier-panel" style={{ textAlign: 'center', padding: '40px' }}>
          <p style={{ color: 'var(--ink-2)' }}>Loading system card specification...</p>
        </div>
      ) : card ? (
        <div className="card-grid">
          {/* Structured Attributes Panel */}
          <div className="card-dossier-panel">
            <div className="card-section-header">
              <div className="card-section-title">
                <IconCpu size={18} />
                <span>Derived Structured Attributes</span>
              </div>
              <span className="badge badge-neutral">Deterministic Mapping</span>
            </div>

            <div className="structured-grid">
              {Object.entries(card.structured_fields).map(([key, value]) => (
                <div key={key} className="structured-item">
                  <span className="structured-label">{key.replace(/_/g, ' ')}</span>
                  <span className="structured-val">{value}</span>
                </div>
              ))}
            </div>

            {/* Statements Side by Side */}
            <div className="statements-grid">
              {/* Intended Use */}
              <div className="statement-card">
                <div className="statement-header">
                  <div className="statement-title">
                    <IconShieldCheck size={16} />
                    <span>Intended Use Statement</span>
                  </div>
                  <button
                    type="button"
                    className="btn btn-sm btn-ghost"
                    onClick={handleRegenerateDrafts}
                    disabled={isRegenerating}
                    title="Regenerate with LLM"
                  >
                    <IconSparkles size={12} />
                    <span>{isRegenerating ? 'Drafting...' : 'AI Draft'}</span>
                  </button>
                </div>
                <textarea
                  className="card-textarea"
                  value={intendedUse}
                  onChange={(e: ChangeEvent<HTMLTextAreaElement>) => setIntendedUse(e.target.value)}
                  placeholder="Describe the intended purpose and approved operational boundaries..."
                />
              </div>

              {/* Known Limitations */}
              <div className="statement-card">
                <div className="statement-header">
                  <div className="statement-title">
                    <IconLayers size={16} />
                    <span>Known Limitations & Exclusions</span>
                  </div>
                  <button
                    type="button"
                    className="btn btn-sm btn-ghost"
                    onClick={handleRegenerateDrafts}
                    disabled={isRegenerating}
                    title="Regenerate with LLM"
                  >
                    <IconRotateCcw size={12} />
                    <span>Reset Draft</span>
                  </button>
                </div>
                <textarea
                  className="card-textarea"
                  value={knownLimits}
                  onChange={(e: ChangeEvent<HTMLTextAreaElement>) => setKnownLimits(e.target.value)}
                  placeholder="Specify out-of-scope tasks, known failure modes, and required human interventions..."
                />
              </div>
            </div>

            {/* Sign-off & Verification Card */}
            <div className="signoff-card">
              <div className="signoff-left">
                <div className="signoff-icon-box">
                  <IconUserCheck size={22} />
                </div>
                <div className="signoff-meta">
                  <span className="signoff-title">Governance Review & Sign-Off</span>
                  <span className="signoff-subtitle">
                    {card.status === 'confirmed'
                      ? `Digitally confirmed by ${card.confirmed_by} on ${formatDate(card.confirmed_at)}`
                      : 'Requires designated reviewer verification before release benchmarking'}
                  </span>
                </div>
              </div>

              {card.status === 'confirmed' ? (
                <div className="confirmed-stamp">
                  <IconCheckCircle size={16} />
                  <span>Confirmed by {card.confirmed_by}</span>
                </div>
              ) : (
                <div className="signoff-form">
                  <input
                    type="text"
                    className="reviewer-input"
                    value={confirmedBy}
                    onChange={(e: ChangeEvent<HTMLInputElement>) => setConfirmedBy(e.target.value)}
                    placeholder="Reviewer Name & Role"
                  />
                  <button
                    type="button"
                    className="btn btn-primary"
                    onClick={handleConfirmCard}
                    disabled={isConfirming}
                  >
                    <IconCheckCircle size={15} />
                    <span>{isConfirming ? 'Confirming...' : 'Sign & Confirm'}</span>
                  </button>
                </div>
              )}
            </div>
          </div>

          {/* Bottom Action Bar */}
          <div className="describe-bottom-bar">
            <div className="describe-bottom-left">
              <Link to="/describe" className="btn btn-secondary">
                <span>&larr; Back to Intake</span>
              </Link>
            </div>

            <Link to="/controls" className="next-step-link">
              <span>Proceed to Safeguard Controls</span>
              <IconArrowRight size={15} />
            </Link>
          </div>
        </div>
      ) : null}
    </div>
  );
}
